namespace: monitoring

prometheus:
  enabled: true
  image:
    repository: prom/prometheus
    tag: v2.48.0
  service:
    type: ClusterIP
    port: 9090
  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi

grafana:
  enabled: true
  image:
    repository: grafana/grafana
    tag: 10.2.0
  service:
    type: ClusterIP
    port: 3000
  persistence:
    enabled: true
    size: 5Gi
  adminPassword: admin123
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

nodeExporter:
  enabled: true
  image:
    repository: prom/node-exporter
    tag: v1.7.0

mongoExporter:
  enabled: true
  image:
    repository: percona/mongodb_exporter
    tag: 0.39.0
  mongodbUri: mongodb://admin:adminpassword@mongodb.ybt.svc.cluster.local:27017/ybt?authSource=admin

kubeStateMetrics:
  enabled: true
  image:
    repository: registry.k8s.io/kube-state-metrics/kube-state-metrics
    tag: v2.10.1

alertmanager:
  enabled: true
  image:
    repository: prom/alertmanager
    tag: v0.26.0
  service:
    type: ClusterIP
    port: 9093
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 512Mi
