apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Values.namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      - "alert_rules.yml"

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'ybt-app'
        static_configs:
          - targets: ['ybt-app.ybt.svc.cluster.local:3000']
        metrics_path: '/metrics'
        scrape_interval: 10s

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter:9100']

      - job_name: 'mongodb-exporter'
        static_configs:
          - targets: ['mongodb-exporter:9216']

      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics:8080']

  alert_rules.yml: |
    groups:
      - name: ybt-app
        rules:
          - alert: HighErrorRate
            expr: rate(http_requests_total{status_code=~"5.."}[5m]) > 0.1
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "High error rate detected"
              description: "Error rate is {{ $value }} errors per second"

          - alert: MongoDBConnectionDown
            expr: mongo_connection_status == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "MongoDB connection is down"
              description: "MongoDB connection has been down for more than 1 minute"

          - alert: HighResponseTime
            expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High response time detected"
              description: "95th percentile response time is {{ $value }} seconds"

      - name: kubernetes
        rules:
          - alert: PodCrashLoopBackOff
            expr: kube_pod_status_phase{phase="Running"} == 0 and kube_pod_status_phase{phase="Failed"} == 1
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Pod is in CrashLoopBackOff"
              description: "Pod {{ $labels.pod }} has been restarting repeatedly"

          - alert: HighMemoryUsage
            expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) > 0.8
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High memory usage detected"
              description: "Container {{ $labels.container }} is using {{ $value }}% of its memory limit"
