apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ybt
data:
  PORT: "3000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ybt-app
  namespace: ybt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ybt-app
  template:
    metadata:
      labels:
        app: ybt-app
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: app
          image: docker.io/samsorrahman/devops-ybt:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-uri
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PORT
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ybt-app
  namespace: ybt
spec:
  selector:
    app: ybt-app
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
