apiVersion: batch/v1
kind: Job
metadata:
  name: seed-data
  namespace: ybt
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: seed
          image: docker.io/samsorrahman/devops-ybt:latest
          imagePullPolicy: IfNotPresent
          command: ["node", "seed.js"]
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-uri
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
