name: CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

env:
  NODE_VERSION: '20'
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}

jobs:
  lint:
    name: Lint JavaScript (standard)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install --omit=dev --no-audit --no-fund

      - name: Auto-fix lint issues
        run: npx --yes standard --fix "**/*.js"

      - name: Verify lint
        run: npx --yes standard "**/*.js"

  sca:
    name: Security Scan (SCA)
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install --omit=dev --no-audit --no-fund

      - name: npm audit (report only)
        run: npm audit --audit-level=high || true

      - name: Run Trivy filesystem scan (SCA)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          ignore-unfixed: true
          scanners: vuln,secret,config,license
          format: table
          severity: CRITICAL,HIGH,MEDIUM
          exit-code: '0'
          path: .

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [ sca ]
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

      - name: Trivy image scan (report only)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          format: table
          ignore-unfixed: true
          severity: CRITICAL,HIGH,MEDIUM
          exit-code: '0'

  docker-scout:
    name: Docker Security Scan (Scout)
    runs-on: ubuntu-latest
    needs: [docker]  # This ensures that the Docker build happens before the security scan
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Docker Scout (Security scanning)
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ env.DOCKER_IMAGE }}:latest
          only-severities: critical,high
          exit-code: true
          summary: true
          format: json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          

